sudo: false
language: objective-c
osx_image: xcode9.4.1

script:
- swift package generate-xcodeproj --enable-code-coverage
- xcodebuild -project FileUtils.xcodeproj -scheme FileUtils-Package test

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
